name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'chore(master): release')"
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.12.0
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Create PR with dist folder
        uses: googleapis/code-suggester@v4
        env:
          ACCESS_TOKEN: ${{ secrets.PAT }}
        with:
          command: pr
          upstream_repo: repofmt-action
          upstream_owner: samdouble
          description: Build dist folder
          title: "chore: build dist"
          message: "chore: build dist"
          labels: automated pr
          branch: build-dist
          primary: master
          force: true
          git_dir: .
          fork: false

  release-please-action:
    if: "!contains(github.event.head_commit.message, 'chore(master): release')"
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT }}
          release-type: node
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: master
          include-component-in-tag: true

  release-please-lib:
    if: "!contains(github.event.head_commit.message, 'chore(master): release')"
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT }}
          release-type: node
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: master
          path: lib
          include-component-in-tag: true
